swagger: "2.0"
info:
  description: "ProductsService"
  version: "1.0.0"
  title: "Swagger Products Contract"
host: "docker-e2e-tests.huebl.net"
basePath: "/api"

schemes:
  - "https"
  - "http"
paths:
  /products:
    post:
      summary: "Add a new products"
      description: ""
      operationId: "addProduct"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Products to be added"
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        201:
          description: "successful created operation"
          schema:
            $ref: "#/definitions/Product"
        405:
          description: "Invalid input"

  /product/{productId}:
    get:
      tags:
        - "product"
      summary: "Find product by ID"
      description: "Returns a single product"
      operationId: "getProductById"
      produces:
        - "application/json"
      parameters:
        - name: "productId"
          in: "path"
          description: "ID of product to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        400:
          description: "Invalid ID supplied"
        404:
          description: "product not found"
      security:
        - api_key: []
    put:
      tags:
        - "product"
      summary: "Updates a product in the store with form data"
      description: ""
      operationId: "updateProductWithForm"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/json"
      parameters:
        - name: "productId"
          in: "path"
          description: "ID of product that needs to be updated"
          required: true
          type: "integer"
          format: "int64"
        - name: "name"
          in: "formData"
          description: "Updated name of the product"
          required: false
          type: "string"

      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        405:
          description: "Invalid input"

    delete:
      tags:
        - "product"
      summary: "Deletes a product"
      description: ""
      operationId: "deleteProduct"
      produces:
        - "application/json"
      parameters:
        - name: "productId"
          in: "path"
          description: "product id to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "operation successful"
        400:
          description: "Invalid ID supplied"
        404:
          description: "product not found"

definitions:
  Product:
    type: "object"
    required:
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "Product One"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"